language: cpp
os: linux
compiler: gcc
sudo: required
dist: xenial

addons:
  apt:
    packages:
      - cmake
      - g++-4.8
      - libboost-all-dev
      
before-install:
    - apt-get -qq update
    - apt-get install -y cmake libboost-all-dev

before_script:
    - mkdir build && cd build
    - cmake ..

script:
    - make