language: cpp
os: linux
compiler: gcc
sudo: required
dist: xenial

addons:
  apt:
    packages:
      - cmake
      - g++-4.8

before_script:
    # cmake build of the project
    - mkdir build && cd build
    - cmake ..

script:
    - make