language: cpp
os: linux
compiler: gcc
sudo: required
dist: xenial
      
before-install:
    - apt-get -qq update
    - apt-get install -y cmake libboost-all-dev

script:
    - mkdir build && cd build
    - cmake ..
    - make